.\" Manpage for wtype.
.TH wtype 1 "23 November 2020" "0.4" "wtype man page"
.SH NAME
wtype \- xdotool type for Wayland
.SH SYNOPSIS
.B wtype
[TEXT]

.B wtype
[OPTION_OR_TEXT]... -- [TEXT]...

.B wtype
[OPTION_OR_TEXT] -

.SH DESCRIPTION
.PP
wtype is a Wayland tool that allows you to simulate keyboard input like xdotool type for X11.
This is accomplished via the virtual-keyboard Wayland protocol.

.SH OPTIONS
Modifier can be one of "shift", "capslock", "ctrl", "logo", "win", "alt", "altgr".
Beware that the modifiers get released automatically once the program terminates.

Named keys are resolved by libxkbcommon, valid identifiers include "Left" and
"Home".

.TP
.BR \-M\ \fIMOD\fR
Press modifier MOD.

.TP
.BR \-m\ \fIMOD\fR
Release modifier MOD.

.TP
.BR \-P\ \fIKEY\fR
Press key KEY.

.TP
.BR \-p\ \fIKEY\fR
Release key KEY.

.TP
.BR \-k\ \fIKEY\fR
Type (press and release) key KEY.

.TP
.BR \-d\ \fITIME\fR
Sleep for TIME milliseconds between keystrokes when typing texts.
Can be used multiple times, default 0.
.TP

.BR \-s\ \fITIME\fR
Sleep for TIME milliseconds before interpreting the following options. This
can be used to perform more complicated modifier sequences.

.TP
.BR \-
Read text to type from stdin. This option can appear only once.

.SH BUGS
No known bugs.

.SH AUTHOR
wtype has been started by Josef Gajdusek.
Man page is written by Michael 'jubalh' Vetter.
